language: node_js
node_js: '10'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
  node_modules: true
script: 
  - yarn run test:coverage
after_success:
  - cat ./coverage/lcov.info | node node_modules/.bin/coveralls